apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
        - name: grafana-app
          image: grafana/grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
          - name: GF_SERVER_HTTP_PORT
            value: "3000"
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
          - name: GF_SERVER_ROOT_URL
            value: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-app
  name: grafana-app-svc
  namespace: default
spec: 
  ports:
  - port:  3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-app
  type: LoadBalancer
