apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-kredis-sample
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: stable.example.com/v1
    kind: KRedis
    name: kredis-sample
  metrics:
    type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60

  