apiVersion: stable.example.com/v1
kind: KRedis
metadata:
  labels:
    app.kubernetes.io/name: kredis
    app.kubernetes.io/instance: kredis-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: kredis-sample
spec:
  # TODO(user): Add fields here
  replicas: 1
  masters: 2
  image: public.ecr.aws/x8r0y3u4/redis-cluster:latest
  memory: 1gb
  basePort: 10000
  resource:
    requests:
      cpu: "2"
      memory: "2000Mi"
