apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: public.ecr.aws/x8r0y3u4/hpa-test:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: svc-web
  namespace: default
spec: 
  ports:
  - port:  80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
